import * as Wi from "react-icons/wi";
export const iconMap = {
    200: <Wi.WiDayThunderstorm />,
    201: <Wi.WiDayThunderstorm />,
    202: <Wi.WiDayThunderstorm />,
    210: <Wi.WiDayThunderstorm />,
    211: <Wi.WiDayThunderstorm />,
    212: <Wi.WiDayThunderstorm />,
    221: <Wi.WiDayThunderstorm />,
    230: <Wi.WiDayThunderstorm />,
    231: <Wi.WiDayThunderstorm />,
    232: <Wi.WiDayThunderstorm />,
    300: <Wi.WiDayShowers />,
    301: <Wi.WiDayShowers />,
    302: <Wi.WiDayShowers />,
    310: <Wi.WiDayShowers />,
    311: <Wi.WiDayShowers />,
    312: <Wi.WiDayShowers />,
    313: <Wi.WiDayShowers />,
    314: <Wi.WiDayShowers />,
    321: <Wi.WiDayShowers />,
    500: <Wi.WiDayRain />, //day/night
    501: <Wi.WiDayRain />, //day/night
    502: <Wi.WiDayRain />, //day/night
    503: <Wi.WiDayRain />, //day/night
    504: <Wi.WiDayRain />, //day/night
    511: <Wi.WiSnow />,
    520: <Wi.WiDayShowers />,
    521: <Wi.WiDayShowers />,
    522: <Wi.WiDayShowers />,
    531: <Wi.WiDayShowers />,
    600: <Wi.WiSnow />,
    601: <Wi.WiSnow />,
    602: <Wi.WiSnow />,
    611: <Wi.WiSnow />,
    612: <Wi.WiSnow />,
    613: <Wi.WiSnow />,
    615: <Wi.WiSnow />,
    616: <Wi.WiSnow />,
    620: <Wi.WiSnow />,
    621: <Wi.WiSnow />,
    622: <Wi.WiSnow />,
    701: <Wi.WiDayFog />,
    711: <Wi.WiDayFog />,
    721: <Wi.WiDayFog />,
    731: <Wi.WiDayFog />,
    741: <Wi.WiDayFog />,
    751: <Wi.WiDayFog />,
    761: <Wi.WiDayFog />,
    762: <Wi.WiDayFog />,
    771: <Wi.WiDayFog />,
    781: <Wi.WiDayFog />,
    800: <Wi.WiDaySunny />, //day/night
    801: <Wi.WiDayCloudy />, //day/night
    802: <Wi.WiNightCloudyHigh />,
    803: <Wi.WiCloudy />,
    804: <Wi.WiCloudy />
};

export const nightIconMap = {
    200: <Wi.WiNightAltThunderstorm />,
    201: <Wi.WiNightAltThunderstorm />,
    202: <Wi.WiNightAltThunderstorm />,
    210: <Wi.WiNightAltThunderstorm />,
    211: <Wi.WiNightAltThunderstorm />,
    212: <Wi.WiNightAltThunderstorm />,
    221: <Wi.WiNightAltThunderstorm />,
    230: <Wi.WiNightAltThunderstorm />,
    231: <Wi.WiNightAltThunderstorm />,
    232: <Wi.WiNightAltThunderstorm />,
    300: <Wi.WiNightAltShowers />,
    301: <Wi.WiNightAltShowers />,
    302: <Wi.WiNightAltShowers />,
    310: <Wi.WiNightAltShowers />,
    311: <Wi.WiNightAltShowers />,
    312: <Wi.WiNightAltShowers />,
    313: <Wi.WiNightAltShowers />,
    314: <Wi.WiNightAltShowers />,
    321: <Wi.WiNightAltShowers />,
    500: <Wi.WiNightAltRain />, //day/night
    501: <Wi.WiNightAltRain />, //day/night
    502: <Wi.WiNightAltRain />, //day/night
    503: <Wi.WiNightAltRain />, //day/night
    504: <Wi.WiNightAltRain />, //day/night
    511: <Wi.WiSnow />,
    520: <Wi.WiNightAltShowers />,
    521: <Wi.WiNightAltShowers />,
    522: <Wi.WiNightAltShowers />,
    531: <Wi.WiNightAltShowers />,
    600: <Wi.WiSnow />,
    601: <Wi.WiSnow />,
    602: <Wi.WiSnow />,
    611: <Wi.WiSnow />,
    612: <Wi.WiSnow />,
    613: <Wi.WiSnow />,
    615: <Wi.WiSnow />,
    616: <Wi.WiSnow />,
    620: <Wi.WiSnow />,
    621: <Wi.WiSnow />,
    622: <Wi.WiSnow />,
    701: <Wi.WiNightFog />,
    711: <Wi.WiNightFog />,
    721: <Wi.WiNightFog />,
    731: <Wi.WiNightFog />,
    741: <Wi.WiNightFog />,
    751: <Wi.WiNightFog />,
    761: <Wi.WiNightFog />,
    762: <Wi.WiNightFog />,
    771: <Wi.WiNightFog />,
    781: <Wi.WiNightFog />,
    800: <Wi.WiNightClear />, //day/night
    801: <Wi.WiNightAltCloudy />, //day/night
    802: <Wi.WiNightCloudyHigh />,
    803: <Wi.WiCloudy />,
    804: <Wi.WiCloudy />
};